### ISSUE TITLE
[SUGGESTION] Include all dependent resources (css/js)

### ISSUE THREAD

**Issue by mfn** [mll-lab/laravel-graphql-playground#5]
It's hard to believe but I had the case where I just installed it/ set it up and later on travel I didn't have wifi and couldn't even use it in my local environment :-(

Are you open to make a complete static snapshot of all the dependencies, so the web part is essentially self-contained?

**Comment by spawnia** [comment]
Definitely believe you 😃 

I like how the current approach is pretty light on maintenance, since it always gets the newest version. I would like to avoid putting the assets into the project directly.

How about we add an artisan command for fetching the assets to local storage and change the template so it uses the local assets if they exists?

**Comment by mfn** [comment]
> How about we add an artisan command for fetching the assets to local storage and change the template so it uses the local assets if they exists?

That's some creative idea ... 😄 No idea how this can work, but I for one would be glad to have it offline.

**Comment by mfn** [comment]
Wow, that is so much appreciated 🙏
