### ISSUE TITLE
Announcement "Retiring Graphql Playground"

### ISSUE THREAD

**Issue by robsontenorio** [mll-lab/laravel-graphql-playground#54]
Considering this post:

https://github.com/graphql/graphql-playground/issues/1143

Do you have any intention to publish a new package for GraphiQL ?

**Comment by mfn** [comment]
That would be interesting…

I never fully understood in which direction GraphiQL went. Their initial version was a primitive set of HTML+JS and thus another project https://github.com/rebing/graphql-laravel/blob/master/resources/views/graphiql.php just "amalgated" the sources into the project itself; due to some customization a cleaner integration wasn't possible.

But a few years ago GraphiQL turned into behemoth you needed to compile with lots-o-dependencies I never fully understood, that's why the integrated version in rebing/graphql-laravel was never updated.

(it also wasn't removed or separated from above package because having this out of the box on dev machines is just really extremely convenient)

**Comment by spawnia** [comment]
I might do one for Altair, considering https://github.com/XKojiMedia/laravel-altair-graphql is not maintained actively.

**Comment by robsontenorio** [comment]
@spawnia currently Playground works great. But there are lacks of updates and new features like “explorer”. 

I would go with big players like Graphiql. But it is just a suggestion.

**Comment by mfn** [comment]
> `DISCLAIMER: This is a port of laravel-graphql-playground from @spawnia of mll-lab, but for Altair GraphQL Client.`

Oh 😅

**Comment by imolorhe** [comment]
Yup! Please anyone that wants to maintain https://github.com/XKojiMedia/laravel-altair-graphql is very welcome to do so 😄  I don't work with PHP or laravel regularly enough to keep maintaining it

**Comment by acao** [comment]
@robsontenorio I maintain both graphiql or graphql-playground. Impressed you think I'm a big player, I just make GraphiQL in my free time. @imolorhe is a co-maintainer :)
